Repository ministryofjustice/hmpps-probation-integration-services, pull requests merged in 2022-10, with the labels that each got.

#210 PI-317 Added risk assessment scores consumer
  .github/workflows/deploy.yml
  .idea/runConfigurations/risk_assessment_scores_to_delius.xml
  libs/commons/src/main/kotlin/uk/gov/justice/digital/hmpps/datetime/ZonedDateTimeDeserializer.kt
  projects/risk-assessment-scores-to-delius/README.md
  projects/risk-assessment-scores-to-delius/build.gradle.kts
  projects/risk-assessment-scores-to-delius/deploy/values-dev.yml
  projects/risk-assessment-scores-to-delius/deploy/values-preprod.yml
  projects/risk-assessment-scores-to-delius/deploy/values-prod.yml
  projects/risk-assessment-scores-to-delius/deploy/values.yml
  projects/risk-assessment-scores-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/MessageGenerator.kt
  projects/risk-assessment-scores-to-delius/src/dev/resources/db/h2.sql
  projects/risk-assessment-scores-to-delius/src/dev/resources/db/oracle.sql
  projects/risk-assessment-scores-to-delius/src/dev/resources/messages/ogrs-scores-determined.json
  projects/risk-assessment-scores-to-delius/src/dev/resources/messages/rsr-scores-determined.json
  projects/risk-assessment-scores-to-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/IntegrationTest.kt
  projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/exception/FailureToUpdateRiskScores.kt
  projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/RiskScoreService.kt
  projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/listener/MessageListener.kt
  projects/risk-assessment-scores-to-delius/src/main/resources/application.yml
  projects/risk-assessment-scores-to-delius/src/test/kotlin/uk/gov/justice/hmpps/listener/MessageListenerTest.kt
Labels: enhancement

#215 PI-451 Include timestamp for allocations and contacts
  projects/prison-custody-status-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/recall/RecallService.kt
  projects/prison-custody-status-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/release/ReleaseService.kt
  projects/prison-custody-status-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/listener/MessageListener.kt
  projects/prison-custody-status-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/recall/RecallServiceTest.kt
  projects/prison-custody-status-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/release/ReleaseServiceTest.kt
  projects/prison-custody-status-to-delius/src/test/kotlin/uk/gov/justice/hmpps/listener/MessageListenerTest.kt
Labels: bug

#216 Fix repository standards compliance badge
  README.md
Labels: bug

#223 Fix registrationId typo in project template
  templates/projects/message-listener-with-api-client/src/main/kotlin/uk/gov/justice/digital/hmpps/config/FeignOAuth2Config.kt
Labels: bug

#220 PI-442 Suppress arr-pm CVE-2022-39224 in Logstash image
  projects/person-search-index-from-delius/.trivyignore
Labels: dependencies

#219 PI-442 Added a set of shared tools and base images
  .github/dependabot.yml
  .github/workflows/tools.yml
  buildSrc/src/main/kotlin/uk/gov/justice/digital/hmpps/plugins/JibConfigPlugin.kt
  projects/person-search-index-from-delius/container/Dockerfile
  tools/build.gradle.kts
  tools/eclipse-temurin/17-jre/Dockerfile
  tools/eclipse-temurin/17-jre/build.gradle.kts
  tools/opensearch-logstash/8/Dockerfile
  tools/opensearch-logstash/8/build.gradle.kts
  tools/settings.gradle.kts
Labels: enhancement

#254 PI-474
  doc/design/create-and-vary-a-licence/api/search-offenders-by-team.yaml
Labels: documentation

#250 Fix SSM parameter check for non-existent parameters
  .github/workflows/deploy.yml
Labels: bug

#295 PI-517 Create ADR for GitHub releases and change log publication
  doc/adr/0008-create-release-and-publish-changelog.md
Labels: documentation

#298 PI-520 Fix multiline Trivy output
  .github/workflows/security.yml
Labels: bug

#286 PI-483 Key Worker API for Approved Premises
  .github/workflows/deploy.yml
  projects/approved-premises-and-delius/build.gradle.kts
  projects/approved-premises-and-delius/deploy/values-dev.yml
  projects/approved-premises-and-delius/deploy/values-preprod.yml
  projects/approved-premises-and-delius/deploy/values.yml
  projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ApprovedPremisesGenerator.kt
  projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/MessageGenerator.kt
  projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ProbationAreaGenerator.kt
  projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/StaffGenerator.kt
  projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/TeamGenerator.kt
  projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/UserGenerator.kt
  projects/approved-premises-and-delius/src/dev/resources/messages/example-message.json
  projects/approved-premises-and-delius/src/dev/resources/simulations/__files/hmpps-auth-token-body.json
  projects/approved-premises-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/IntegrationTest.kt
  projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/ApiController.kt
  projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/StaffController.kt
  projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/approvedpremises/ApprovedPremises.kt
  projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/approvedpremises/ApprovedPremisesRepository.kt
  projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/probationarea/LocalDeliveryUnit.kt
  projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/probationarea/ProbationArea.kt
  projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/probationarea/ProbationDeliveryUnit.kt
  projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/referencedata/ReferenceData.kt
  projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/staff/Staff.kt
  projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/staff/StaffRepository.kt
  projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/team/Team.kt
  projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/model/StaffResponse.kt
  projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/StaffService.kt
  projects/approved-premises-and-delius/src/main/resources/application.yml
  projects/approved-premises-and-delius/src/main/resources/local-public-key.pub
  projects/approved-premises-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/controller/StaffControllerTest.kt
  projects/approved-premises-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/StaffServiceTest.kt
Labels: enhancement
