Repository ministryofjustice/hmpps-probation-integration-services, pull requests merged in 2023-02, with the labels that each got.

#825 PI-766 Set default response type to JSON in OpenAPI specs
  projects/approved-premises-and-delius/src/main/resources/application.yml
  projects/approved-premises-and-oasys/src/main/resources/application.yml
  projects/custody-key-dates-and-delius/src/main/resources/application.yml
  projects/pre-sentence-reports-to-delius/src/main/resources/application.yml
  projects/unpaid-work-and-delius/src/main/resources/application.yml
  projects/workforce-allocations-to-delius/src/main/resources/application.yml
  templates/projects/api-client-and-server/src/main/resources/application.yml
  templates/projects/api-server/src/main/resources/application.yml
  templates/projects/message-listener-with-api-client-and-server/src/main/resources/application.yml
Labels: enhancement

#877 PI-819 Auto-label PRs based on Jira issue type
  .github/workflows/label-pull-requests.yml
Labels: enhancement

#879 PI-822 Improve LDAP query performance for email lookups
  projects/manage-pom-cases-and-delius/build.gradle.kts
  projects/manage-pom-cases-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/App.kt
  projects/manage-pom-cases-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/ldap/LdapService.kt
  projects/manage-pom-cases-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/ldap/LdapUser.kt
  projects/manage-pom-cases-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/services/ProbationRecordService.kt
  projects/manage-pom-cases-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/ldap/LdapServiceTest.kt
  projects/manage-pom-cases-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/services/ProbationRecordServiceTest.kt
  projects/workforce-allocations-to-delius/build.gradle.kts
  projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/App.kt
  projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/user/LdapUserRepository.kt
  projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/LdapService.kt
  projects/workforce-allocations-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/LdapServiceTest.kt
Labels: bug

#890 PI-825 Auto-label Trivy suppression PRs
  .github/workflows/suppress-trivy.yml
Labels: enhancement

#892 Bump Logstash base image to from 8.4.0 to 8.6.1
  projects/person-search-index-from-delius/container/Dockerfile
Labels: dependencies, docker

#898 PI-819 Fix for unexpected characters in PR title
  .github/workflows/label-pull-requests.yml
Labels: bug

#914 PI-838 Handle multiple other offences in PSR context API
  projects/pre-sentence-reports-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/courtreport/CourtReportRepository.kt
Labels: bug

#901 PI-779 Add Pingdom check and certificate during bootstrap
  .github/workflows/bootstrap.yml
  templates/certificate.yml
Labels: enhancement

#886 PI-789 process OGRS determined message
  libs/messaging/src/main/kotlin/uk/gov/justice/digital/hmpps/message/HmppsDomainEvent.kt
  projects/risk-assessment-scores-to-delius/build.gradle.kts
  projects/risk-assessment-scores-to-delius/deploy/database/access.yml
  projects/risk-assessment-scores-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/MessageGenerator.kt
  projects/risk-assessment-scores-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/risk-assessment-scores-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ContactTypeGenerator.kt
  projects/risk-assessment-scores-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/DatasetGenerator.kt
  projects/risk-assessment-scores-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/DisposalGenerator.kt
  projects/risk-assessment-scores-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/DisposalTypeGenerator.kt
  projects/risk-assessment-scores-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/EventGenerator.kt
  projects/risk-assessment-scores-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/MainOffenceGenerator.kt
  projects/risk-assessment-scores-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/OffenceGenerator.kt
  projects/risk-assessment-scores-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/PersonGenerator.kt
  projects/risk-assessment-scores-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/PersonManagerGenerator.kt
  projects/risk-assessment-scores-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ReferenceDataGenerator.kt
  projects/risk-assessment-scores-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/StaffGenerator.kt
  projects/risk-assessment-scores-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/TeamGenerator.kt
  projects/risk-assessment-scores-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/UserGenerator.kt
  projects/risk-assessment-scores-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/repository/DataRepositories.kt
  projects/risk-assessment-scores-to-delius/src/dev/resources/messages/ogrs-scores-determined-update.json
  projects/risk-assessment-scores-to-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/IntegrationTest.kt
  projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/RiskAssessmentService.kt
  projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/entity/Contact.kt
  projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/entity/Event.kt
  projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/entity/OGRSAssessment.kt
  projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/entity/Person.kt
  projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/entity/PersonManager.kt
  projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/entity/ReferenceData.kt
  projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/entity/Staff.kt
  projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/entity/Team.kt
  projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
  projects/risk-assessment-scores-to-delius/src/main/resources/application.yml
  projects/risk-assessment-scores-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/RiskAssessmentServiceTest.kt
  projects/risk-assessment-scores-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/messaging/HandlerTest.kt
Labels: enhancement

#918 PI-847 Remove manual DB access step
  .github/workflows/access.yml
Labels: enhancement

#924 PI-837 change cron for dev env
  projects/person-search-index-from-delius/deploy/values-dev.yml
Labels: bug

#925 PI-844 Update to not require probation area code as part of premises detail
  projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ApprovedPremisesGenerator.kt
  projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/EventDetailsGenerator.kt
  projects/approved-premises-and-delius/src/dev/resources/simulations/__files/approved-premises-booking-made.json
  projects/approved-premises-and-delius/src/dev/resources/simulations/__files/approved-premises-person-departed.json
  projects/approved-premises-and-delius/src/dev/resources/simulations/__files/approved-premises-person-not-arrived.json
  projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/approvedpremises/Premises.kt
  projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/approvedpremises/ApprovedPremises.kt
  projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/contact/Contact.kt
  projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/probationarea/ProbationAreaRepository.kt
  projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/ApprovedPremisesService.kt
  projects/approved-premises-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/ApprovedPremisesServiceTest.kt
  projects/tier-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/tier/TierService.kt
Labels: enhancement

#926 PI-852 Increase timeout for pre-sentence service PDF generation
  projects/pre-sentence-reports-to-delius/src/main/resources/application.yml
Labels: bug

#927 PI-853 Handle null event number from OASys
  projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/RiskScoreService.kt
Labels: bug

#928 PI-855 idempotency of terminate nsi
  projects/refer-and-monitor-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/NsiService.kt
Labels: enhancement

#929 PI-857 update team reference to team_id
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/common/entity/person/PersonManager.kt
Labels: bug

#932 PI-860 added status to Document
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/document/Document.kt
Labels: bug

#934 PI-860 added missing fields to Document
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/document/Document.kt
Labels: bug

#936 PI-860 added missing created date
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/document/Document.kt
Labels: bug

#937 PI-851 Add Tier Calculation Required into OGRS Consumer
  projects/risk-assessment-scores-to-delius/deploy/database/access.yml
  projects/risk-assessment-scores-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/risk-assessment-scores-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/DatasetGenerator.kt
  projects/risk-assessment-scores-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ReferenceDataGenerator.kt
  projects/risk-assessment-scores-to-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/IntegrationTest.kt
  projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/RiskAssessmentService.kt
  projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/entity/ManagementTierEvent.kt
  projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/entity/ReferenceData.kt
  projects/risk-assessment-scores-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/RiskAssessmentServiceTest.kt
Labels: enhancement
