Repository ministryofjustice/hmpps-probation-integration-services, pull requests merged in 2023-04, with the labels that each got.

#1258 PI-577 Add offence details, and remove time from release dates
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/EventGenerator.kt
  projects/make-recall-decisions-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/CaseSummaryIntegrationTest.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/Overview.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/casesummary/Event.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/casesummary/Release.kt
  projects/make-recall-decisions-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/CaseSummaryServiceTest.kt
Labels: bug

#1263 PI-577 Add endpoint for Licence Conditions
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/EventGenerator.kt
  projects/make-recall-decisions-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/CaseSummaryIntegrationTest.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/controller/CaseSummaryController.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/LicenceConditions.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/Offence.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/Overview.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/Sentence.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/casesummary/Event.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/CaseSummaryService.kt
Labels: enhancement

#1272 PI-965 Grant audit permission for unpaid-work-and-delius service
  projects/unpaid-work-and-delius/deploy/database/access.yml
Labels: bug

#1276 PI-968 reverted disability provision change
  projects/unpaid-work-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/CaseGenerator.kt
  projects/unpaid-work-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/DisabilityGenerator.kt
  projects/unpaid-work-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ProvisionGenerator.kt
  projects/unpaid-work-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/CaseDetailsIntegrationTest.kt
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/casedetails/CaseMapper.kt
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/casedetails/entity/CaseEntity.kt
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/casedetails/entity/DisabilityEntity.kt
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/casedetails/entity/ProvisionEntity.kt
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/casedetails/model/CaseDetails.kt
Labels: enhancement

#1277 PI-968 reverted disability provision change
  projects/unpaid-work-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/CaseDetailsIntegrationTest.kt
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/casedetails/CaseMapper.kt
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/casedetails/model/CaseDetails.kt
Labels: enhancement

#1279 PI-971 - updated to handle main address correctly
  projects/unpaid-work-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/unpaid-work-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/CaseAddressGenerator.kt
  projects/unpaid-work-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/DatasetGenerator.kt
  projects/unpaid-work-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ReferenceDataGenerator.kt
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/casedetails/CaseMapper.kt
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/casedetails/entity/CaseAddress.kt
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/casedetails/entity/CaseEntity.kt
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/common/entity/Dataset.kt
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/common/entity/PersonalCircumstanceBase.kt
Labels: bug

#1280 PI-577 Add user access endpoint
  libs/dev-tools/src/main/kotlin/uk/gov/justice/digital/hmpps/ReflectionUtils.kt
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/PersonGenerator.kt
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/UserGenerator.kt
  projects/make-recall-decisions-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/UserAccessIntegrationTest.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/controller/UserAccessController.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/Overview.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/UserAccess.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/user/access/Person.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/user/access/UserAccessRepository.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/CaseSummaryService.kt
Labels: enhancement

#1282 PI-966 Parse eventId as a string
  projects/unpaid-work-and-delius/src/dev/resources/messages/upw-assessment-complete.json
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/upwassessment/UPWAssessmentService.kt
Labels: bug

#1304 PI-958 Extend Trivy suppression expiry for known vulnerabilities
  projects/approved-premises-and-delius/.trivyignore
  projects/approved-premises-and-oasys/.trivyignore
  projects/court-case-and-delius/.trivyignore
  projects/create-and-vary-a-licence-and-delius/.trivyignore
  projects/custody-key-dates-and-delius/.trivyignore
  projects/make-recall-decisions-and-delius/.trivyignore
  projects/manage-pom-cases-and-delius/.trivyignore
  projects/offender-events-and-delius/.trivyignore
  projects/pre-sentence-reports-to-delius/.trivyignore
  projects/prison-case-notes-to-probation/.trivyignore
  projects/prison-custody-status-to-delius/.trivyignore
  projects/refer-and-monitor-and-delius/.trivyignore
  projects/risk-assessment-scores-to-delius/.trivyignore
  projects/tier-to-delius/.trivyignore
  projects/unpaid-work-and-delius/.trivyignore
  projects/workforce-allocations-to-delius/.trivyignore
Labels: dependencies, security

#1379 PI-577 Add contact history endpoint
  libs/dev-tools/src/main/kotlin/uk/gov/justice/digital/hmpps/ReflectionUtils.kt
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ContactGenerator.kt
  projects/make-recall-decisions-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/CaseSummaryIntegrationTest.kt
  projects/make-recall-decisions-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/RecommendationIntegrationTest.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/controller/CaseSummaryController.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/ContactHistory.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/casesummary/Contact.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/recommendation/contact/entity/Contact.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/CaseSummaryService.kt
  projects/make-recall-decisions-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/CaseSummaryServiceTest.kt
Labels: enhancement

#1388 PI-998 Handle null additional_offence.offence_date
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/Offence.kt
Labels: bug

#1390 PI-577 Add staff code endpoint
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/PersonGenerator.kt
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/UserGenerator.kt
  projects/make-recall-decisions-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/StaffIntegrationTest.kt
  projects/make-recall-decisions-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/UserAccessIntegrationTest.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/controller/UserController.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/Staff.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/recommendation/provider/entity/Staff.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/user/staff/UserStaffRepository.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/user/staff/entity/Staff.kt
Labels: enhancement

#1409 PI-577 Set staff table name
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/recommendation/provider/entity/Staff.kt
Labels: enhancement

#1411 PI-577 Return 404 for user access when case not found
  projects/make-recall-decisions-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/UserAccessIntegrationTest.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/controller/UserController.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/user/access/UserAccessRepository.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/user/staff/UserStaffRepository.kt
  projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/user/access/UserAccessRepository.kt
Labels: bug

#1419 PI-1007 Handle null sensitive flag, and return system-generated flag
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/ContactHistory.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/casesummary/Contact.kt
  projects/make-recall-decisions-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/CaseSummaryServiceTest.kt
Labels: bug

#1420 PI-1008 Fix group by clause for contact type summary
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ContactGenerator.kt
  projects/make-recall-decisions-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/CaseSummaryIntegrationTest.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/ContactHistory.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/casesummary/Contact.kt
  projects/make-recall-decisions-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/CaseSummaryServiceTest.kt
Labels: bug

#1424 PI-961 Enabled deployment of EPF integration
  projects/effective-proposal-framework-and-delius/deploy/values-dev.yml
  projects/effective-proposal-framework-and-delius/deploy/values-preprod.yml
  projects/effective-proposal-framework-and-delius/deploy/values-prod.yml
Labels: enhancement

#1427 PI-1012 added ENV entry for EPF API
  .github/workflows/end-to-end-tests.yml
Labels: enhancement

#1430 PI-990 Use detailUrl for management-oversight message notes and sensitive flag
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/MessageGenerator.kt
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/StaffGenerator.kt
  projects/make-recall-decisions-and-delius/src/dev/resources/messages/management-oversight-not-recall.json
  projects/make-recall-decisions-and-delius/src/dev/resources/messages/management-oversight-recall.json
  projects/make-recall-decisions-and-delius/src/dev/resources/simulations/__files/management-oversight-detail.json
  projects/make-recall-decisions-and-delius/src/dev/resources/simulations/mappings/make-recall-decisions-api.json
  projects/make-recall-decisions-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/RecommendationIntegrationTest.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/controller/UserController.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/config/FeignConfig.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/alfresco/AlfrescoClient.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/recommendation/provider/StaffRepository.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/recommendation/provider/entity/Staff.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/user/staff/StaffRepository.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/makerecalldecisions/MakeRecallDecisionsClient.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/ManagementOversightRecall.kt
  projects/make-recall-decisions-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/messaging/HandlerTest.kt
  projects/make-recall-decisions-and-delius/tech-docs/source/api-reference.html.md.erb
Labels: enhancement

#1431 PI-1021 Throw error when detailUrl is blank
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
  projects/make-recall-decisions-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/messaging/HandlerTest.kt
Labels: bug

#1434 PI-994 Attempt to fix cleanup job failures
  .github/workflows/cleanup.yml
Labels: bug

#1435 PI-1004 MAW handle CADE contact creation
  projects/workforce-allocations-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/AllocationsDataLoader.kt
  projects/workforce-allocations-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ContactTypeGenerator.kt
  projects/workforce-allocations-to-delius/src/dev/resources/simulations/__files/get-event-allocation-body.json
  projects/workforce-allocations-to-delius/src/dev/resources/simulations/__files/historic-event-allocation-body.json
  projects/workforce-allocations-to-delius/src/dev/resources/simulations/__files/new-event-allocation-body.json
  projects/workforce-allocations-to-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/AllocateEventIntegrationTest.kt
  projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/contact/Contact.kt
  projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/contact/ContactContext.kt
  projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/workforceallocations/AllocationDetail.kt
  projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/AllocateEventService.kt
Labels: enhancement

#1437 PI-1022 Add missing OAuth client config
  projects/make-recall-decisions-and-delius/deploy/values-dev.yml
  projects/make-recall-decisions-and-delius/deploy/values-preprod.yml
  projects/make-recall-decisions-and-delius/deploy/values-prod.yml
Labels: bug

#1438 PI-1022 Fix Feign config for auth token
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/config/MakeRecallDecisionsFeignConfig.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/makerecalldecisions/MakeRecallDecisionsClient.kt
Labels: bug

#1443 PI-1022 Fix Feign config for auth token
  projects/make-recall-decisions-and-delius/deploy/values.yaml
  projects/make-recall-decisions-and-delius/src/main/resources/application.yml
Labels: bug

#1451 PI-633: Complete workforce docs
  projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/resource/AllocationCompletedResource.kt
  projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/resource/AllocationDemandResource.kt
  projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/resource/AllocationDetailResource.kt
  projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/resource/CaseViewResource.kt
  projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/resource/DocumentResource.kt
  projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/resource/PersonResource.kt
  projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/resource/StaffResource.kt
  projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/resource/UserResource.kt
  projects/workforce-allocations-to-delius/tech-docs/source/async-api-reference.html.md.erb
  projects/workforce-allocations-to-delius/tech-docs/source/img/workforce-allocations-to-delius-context-map.png
  projects/workforce-allocations-to-delius/tech-docs/spec/async-api.yaml
Labels: documentation
