Repository ministryofjustice/hmpps-probation-integration-services, pull requests merged in 2023-03, with the labels that each got.

#944 PI-869 Create error on terminated event number
  projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/RiskAssessmentService.kt
  projects/risk-assessment-scores-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/RiskAssessmentServiceTest.kt
Labels: enhancement

#945 PI-870
  projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/RiskAssessmentService.kt
Labels: bug

#942 PI-830 Added contact search indexing pipeline
  projects/person-search-index-from-delius/container/Dockerfile
  projects/person-search-index-from-delius/container/config/logstash.yml
  projects/person-search-index-from-delius/container/config/pipelines.yml
  projects/person-search-index-from-delius/container/logstash.yml
  projects/person-search-index-from-delius/container/management/init-script.sh
  projects/person-search-index-from-delius/container/management/person-search-pipeline.json
  projects/person-search-index-from-delius/container/pipelines.yml
  projects/person-search-index-from-delius/container/pipelines/contact/index/contact-search-template.yml
  projects/person-search-index-from-delius/container/pipelines/contact/logstash-dlq.conf
  projects/person-search-index-from-delius/container/pipelines/contact/logstash-full-load.conf
  projects/person-search-index-from-delius/container/pipelines/contact/logstash-incremental.conf
  projects/person-search-index-from-delius/container/pipelines/contact/statement.sql
  projects/person-search-index-from-delius/container/pipelines/person/index/person-search-pipeline.json
  projects/person-search-index-from-delius/container/pipelines/person/index/person-search-template.json
  projects/person-search-index-from-delius/container/pipelines/person/logstash-dlq.conf
  projects/person-search-index-from-delius/container/pipelines/person/logstash-full-load.conf
  projects/person-search-index-from-delius/container/pipelines/person/logstash-incremental.conf
  projects/person-search-index-from-delius/container/pipelines/person/statement.sql
  projects/person-search-index-from-delius/container/scripts/functions.sh
  projects/person-search-index-from-delius/container/scripts/monitor-reindexing.sh
  projects/person-search-index-from-delius/container/scripts/setup-index.sh
  projects/person-search-index-from-delius/container/scripts/startup.sh
  projects/person-search-index-from-delius/deploy/templates/contact-reindex-cronjob.yml
  projects/person-search-index-from-delius/deploy/templates/index-management-cronjob.yml
  projects/person-search-index-from-delius/deploy/templates/person-reindex-cronjob.yml
  projects/person-search-index-from-delius/deploy/values-dev.yml
  projects/person-search-index-from-delius/deploy/values-preprod.yml
  projects/person-search-index-from-delius/deploy/values-prod.yml
  projects/person-search-index-from-delius/deploy/values.yaml
  projects/person-search-index-from-delius/docker-compose.yml
  projects/person-search-index-from-delius/localstack/sqs-setup.sh
  projects/person-search-index-from-delius/management/build.gradle.kts
  projects/person-search-index-from-delius/management/container/Dockerfile
  projects/person-search-index-from-delius/management/container/index-alias-management.sh
  settings.gradle.kts
Labels: enhancement

#973 PI-830 Reduce batch size for person-search and incremental updates
  projects/person-search-index-from-delius/container/config/logstash.yml
  projects/person-search-index-from-delius/container/scripts/startup.sh
  projects/person-search-index-from-delius/deploy/templates/contact-reindex-cronjob.yml
  projects/person-search-index-from-delius/deploy/templates/person-reindex-cronjob.yml
Labels: enhancement

#976 PI-830 Quote env var for batch size
  projects/person-search-index-from-delius/deploy/templates/contact-reindex-cronjob.yml
  projects/person-search-index-from-delius/deploy/templates/person-reindex-cronjob.yml
Labels: enhancement

#977 PI-879 Only switch indexes after all rows have been loaded
  projects/person-search-index-from-delius/container/pipelines/contact/statement.sql
  projects/person-search-index-from-delius/container/pipelines/person/statement.sql
  projects/person-search-index-from-delius/container/scripts/monitor-reindexing.sh
  projects/person-search-index-from-delius/container/scripts/startup.sh
  projects/person-search-index-from-delius/deploy/values.yaml
Labels: bug

#980 PI-830 Increase batch size for person-full-load pipeline
  projects/person-search-index-from-delius/container/pipelines/person/logstash-full-load.conf
Labels: enhancement

#981 WFP-1876 added staff email to impact endpoint
  projects/workforce-allocations-to-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/ImpactIntegrationTest.kt
  projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/AllocationDemandService.kt
Labels: enhancement

#983 PI-867 Increase stack size for SchemaSpy generation
  .github/workflows/schema-spy.yml
Labels: bug

#982 PI-881 Ignore "missing event number" errors from RSR procedure
  projects/risk-assessment-scores-to-delius/src/dev/resources/messages/no-event-number.json
  projects/risk-assessment-scores-to-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/IntegrationTest.kt
  projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/DeliusValidationError.kt
  projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/RiskScoreService.kt
  projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
  projects/risk-assessment-scores-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/messaging/HandlerTest.kt
Labels: enhancement

#1008 PI-884 Disable sending environment variables to Sentry
  projects/person-search-index-from-delius/container/scripts/functions.sh
  projects/person-search-index-from-delius/container/scripts/monitor-reindexing.sh
  projects/person-search-index-from-delius/container/scripts/setup-index.sh
  projects/person-search-index-from-delius/container/scripts/startup.sh
Labels: bug

#1011 PI-882 Wait for connection to search index before startup
  projects/person-search-index-from-delius/container/scripts/monitor-reindexing.sh
  projects/person-search-index-from-delius/container/scripts/startup.sh
Labels: bug

#1009 PI-774 Migrate secrets from GitHub to Kubernetes
  .github/actions/cloud-platform-auth/action.yml
  .github/actions/cloud-platform-deploy/action.yml
  .github/actions/random-secret/action.yml
  .github/workflows/access.yml
  .github/workflows/bootstrap.yml
  .github/workflows/deploy.yml
  projects/approved-premises-and-delius/deploy/values.yaml
  projects/approved-premises-and-oasys/deploy/values.yaml
  projects/custody-key-dates-and-delius/deploy/values.yaml
  projects/make-recall-decisions-and-delius/deploy/values.yaml
  projects/manage-pom-cases-and-delius/deploy/values.yaml
  projects/offender-events-and-delius/deploy/values.yaml
  projects/person-search-index-from-delius/deploy/values.yaml
  projects/pre-sentence-reports-to-delius/deploy/values.yaml
  projects/prison-case-notes-to-probation/deploy/values.yaml
  projects/prison-custody-status-to-delius/deploy/values.yaml
  projects/refer-and-monitor-and-delius/deploy/values.yaml
  projects/risk-assessment-scores-to-delius/deploy/values.yaml
  projects/tier-to-delius/deploy/values.yaml
  projects/unpaid-work-and-delius/deploy/values.yaml
  projects/workforce-allocations-to-delius/deploy/values.yaml
  templates/projects/api-client-and-server/deploy/values.yaml
  templates/projects/api-server/deploy/values.yaml
  templates/projects/message-listener-with-api-client-and-server/deploy/values.yaml
  templates/projects/message-listener-with-api-client/deploy/values.yaml
  templates/projects/message-listener/deploy/values.yaml
  templates/sqs.tf
Labels: enhancement

#1012 PI-744 Remove unused action input
  .github/workflows/deploy.yml
Labels: bug

#1016 PI-892 Deploy unpaid-work-and-delius to Production
  projects/unpaid-work-and-delius/deploy/values-prod.yml
Labels: enhancement

#1023 PI-861 LAO endpoint for workforce
  projects/workforce-allocations-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/AllocationsDataLoader.kt
  projects/workforce-allocations-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/LimitedAccessDataLoader.kt
  projects/workforce-allocations-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/LimitedAccessGenerator.kt
  projects/workforce-allocations-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/PersonGenerator.kt
  projects/workforce-allocations-to-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/UserGenerator.kt
  projects/workforce-allocations-to-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/LimitedAccessIntegrationTest.kt
  projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/UserAccess.kt
  projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/resource/UserResource.kt
  projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/person/Person.kt
  projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/user/access/UserAccessRepository.kt
  projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/user/access/entity/LimitedAccess.kt
  projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/UserAccessService.kt
Labels: enhancement

#1022 PI-744 Update cron jobs to use new secrets
  projects/person-search-index-from-delius/deploy/templates/contact-reindex-cronjob.yml
  projects/person-search-index-from-delius/deploy/templates/person-reindex-cronjob.yml
Labels: enhancement

#1025 PI-896 Combine Docker push tasks
  projects/person-search-index-from-delius/build.gradle.kts
Labels: bug

#1028 PI-900 Fix CronJob secret references
  projects/person-search-index-from-delius/deploy/templates/contact-reindex-cronjob.yml
  projects/person-search-index-from-delius/deploy/templates/person-reindex-cronjob.yml
Labels: bug

#1029 PI-901 UPW API fix
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/common/model/CommonModels.kt
Labels: bug

#1032 PI-886 Enable feature flagging using Flipt
  .github/actions/cloud-platform-deploy/action.yml
  .github/workflows/tools.yml
  README.md
  libs/commons/build.gradle.kts
  libs/commons/src/main/kotlin/uk/gov/justice/digital/hmpps/config/FliptConfig.kt
  libs/commons/src/main/kotlin/uk/gov/justice/digital/hmpps/flags/FeatureFlags.kt
  libs/commons/src/test/kotlin/uk/gov/justice/digital/hmpps/flags/FeatureFlagsTest.kt
  projects/risk-assessment-scores-to-delius/build.gradle.kts
  projects/risk-assessment-scores-to-delius/deploy/values-prod.yml
  projects/risk-assessment-scores-to-delius/src/dev/resources/simulations/mappings/feature-flags.json
  projects/risk-assessment-scores-to-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/FeatureFlagIntegrationTest.kt
  projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
  projects/risk-assessment-scores-to-delius/src/main/resources/application.yml
  projects/risk-assessment-scores-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/messaging/HandlerTest.kt
  settings.gradle.kts
  tools/eclipse-temurin/17-jre-alpine/build.gradle.kts
  tools/eclipse-temurin/17-jre-jammy/build.gradle.kts
  tools/eclipse-temurin/19-jre-jammy/build.gradle.kts
  tools/feature-flags/deploy/Chart.yaml
  tools/feature-flags/deploy/values.yaml
  tools/opensearch-logstash/8/build.gradle.kts
Labels: enhancement

#1033 PI-886 Automate Auth0 configuration
  .github/workflows/tools.yml
  tools/feature-flags/deploy/auth0/actions/Check GitHub teams/code.js
  tools/feature-flags/deploy/auth0/config.json
  tools/feature-flags/deploy/auth0/tenant.yaml
Labels: enhancement

#1035 PI-890 Switch to Docker build action
  .github/actions/build-and-test/action.yml
  .github/actions/check-changes/action.yml
  .github/actions/docker-build/action.yml
  .github/workflows/branch.yml
  .github/workflows/build.yml
  .github/workflows/pipeline.yml
  .github/workflows/tools.yml
  projects/person-search-index-from-delius/build.gradle.kts
  projects/person-search-index-from-delius/settings.gradle.kts
Labels: enhancement

#1078 PI-907 Fix image pushes on the main branch pipeline
  .github/workflows/build.yml
Labels: bug

#1083 PI-908 Set branch when building tech-docs
  .github/workflows/docs.yml
Labels: bug

#1085 PI-907 Fix jq arg for checking changes
  .github/workflows/build.yml
Labels: bug

#1089 PI-909 Pin Flipt version, increase replica count, and set alert channel
  tools/feature-flags/deploy/values.yaml
Labels: bug

#1091 PI-910 project file tidy up
  projects/approved-premises-and-delius/src/dev/resources/local-public-key.pub
  projects/approved-premises-and-delius/src/main/resources/application.yml
  projects/approved-premises-and-oasys/src/dev/resources/local-public-key.pub
  projects/create-and-vary-a-licence-and-delius/src/main/resources/application.yml
  projects/custody-key-dates-and-delius/src/main/resources/application.yml
  projects/make-recall-decisions-and-delius/src/main/resources/application.yml
  projects/manage-pom-cases-and-delius/src/main/resources/application.yml
  projects/offender-events-and-delius/src/main/resources/application.yml
  projects/pre-sentence-reports-to-delius/src/dev/resources/local-public-key.pub
  projects/prison-custody-status-to-delius/src/main/resources/application.yml
  projects/refer-and-monitor-and-delius/src/main/resources/application.yml
  projects/risk-assessment-scores-to-delius/src/main/resources/application.yml
  projects/tier-to-delius/src/main/resources/application.yml
  projects/unpaid-work-and-delius/src/dev/resources/local-public-key.pub
  projects/unpaid-work-and-delius/src/main/resources/application.yml
  projects/workforce-allocations-to-delius/src/dev/resources/local-public-key.pub
  projects/workforce-allocations-to-delius/src/dev/resources/schema.ldif
  templates/projects/api-client-and-server/src/main/resources/application.yml
  templates/projects/api-server/src/main/resources/application.yml
  templates/projects/message-listener-with-api-client-and-server/src/main/resources/application.yml
  templates/projects/message-listener-with-api-client/src/main/resources/application.yml
  templates/projects/message-listener/src/main/resources/application.yml
Labels: enhancement

#1095 Fix Flipt URL
  projects/risk-assessment-scores-to-delius/deploy/values-prod.yml
Labels: bug

#1094 PI-911 Create GitHub issue for DB access workflow approval
  .github/workflows/access.yml
Labels: enhancement

#1127 PI-919 Add Sentry cron monitoring
  .github/workflows/bootstrap.yml
  projects/person-search-index-from-delius/container/scripts/startup.sh
  projects/person-search-index-from-delius/deploy/templates/contact-reindex-cronjob.yml
  projects/person-search-index-from-delius/deploy/templates/person-reindex-cronjob.yml
Labels: enhancement

#1124 PI-893 Extend Trivy suppression for CVE-2023-24998 in Apache Commons FileUpload
  projects/approved-premises-and-delius/.trivyignore
  projects/approved-premises-and-oasys/.trivyignore
  projects/create-and-vary-a-licence-and-delius/.trivyignore
  projects/custody-key-dates-and-delius/.trivyignore
  projects/manage-pom-cases-and-delius/.trivyignore
  projects/pre-sentence-reports-to-delius/.trivyignore
  projects/prison-case-notes-to-probation/.trivyignore
  projects/refer-and-monitor-and-delius/.trivyignore
  projects/tier-to-delius/.trivyignore
  projects/unpaid-work-and-delius/.trivyignore
  projects/workforce-allocations-to-delius/.trivyignore
Labels: dependencies, security

#1131 PI-924 - API fixes
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/common/entity/Dataset.kt
Labels: bug

#1129 PI-923 Add support for publishing draft tech docs
  .github/actions/render-project-template/action.yml
  .github/workflows/cleanup.yml
  .github/workflows/docs.yml
Labels: enhancement

#1140 PI-577 Personal Details endpoint for Make Recall Decisions
  projects/make-recall-decisions-and-delius/build.gradle.kts
  projects/make-recall-decisions-and-delius/deploy/values-dev.yml
  projects/make-recall-decisions-and-delius/deploy/values-preprod.yml
  projects/make-recall-decisions-and-delius/deploy/values-prod.yml
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/AddressGenerator.kt
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/MessageGenerator.kt
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/PersonGenerator.kt
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/repository/PersonManagerRepository.kt
  projects/make-recall-decisions-and-delius/src/dev/resources/local-public-key.pub
  projects/make-recall-decisions-and-delius/src/dev/resources/messages/management-oversight-not-recall.json
  projects/make-recall-decisions-and-delius/src/dev/resources/messages/management-oversight-recall.json
  projects/make-recall-decisions-and-delius/src/dev/resources/messages/recommendation-started.json
  projects/make-recall-decisions-and-delius/src/dev/resources/simulations/__files/hmpps-auth-token-body.json
  projects/make-recall-decisions-and-delius/src/dev/resources/simulations/mappings/hmpps-auth.json
  projects/make-recall-decisions-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/CaseSummaryIntegrationTest.kt
  projects/make-recall-decisions-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/RecommendationIntegrationTest.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/controller/CaseSummaryController.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/PersonalDetails.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/casesummary/CaseSummaryAddress.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/casesummary/CaseSummaryPerson.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/referencedata/entity/ReferenceData.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/CaseSummaryService.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/ManagementOversightRecall.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/RecommendationStarted.kt
  projects/make-recall-decisions-and-delius/src/main/resources/application.yml
  projects/make-recall-decisions-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/api/controller/CaseSummaryControllerTest.kt
  projects/make-recall-decisions-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/messaging/HandlerTest.kt
  projects/make-recall-decisions-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/CaseSummaryServiceTest.kt
  projects/make-recall-decisions-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/RecommendationStartedTest.kt
  projects/make-recall-decisions-and-delius/tech-docs/config/tech-docs.yml
  projects/make-recall-decisions-and-delius/tech-docs/source/api-reference.html.md.erb
  projects/make-recall-decisions-and-delius/tech-docs/source/draft-api-spec.yaml
  templates/projects/api-client-and-server/src/dev/resources/local-public-key.pub
  templates/projects/api-server/src/dev/resources/local-public-key.pub
  templates/projects/message-listener-with-api-client-and-server/src/dev/resources/local-public-key.pub
Labels: enhancement

#1198 PI-893 Suppress vulnerability alerts for Spring Framework and Json-smart
  projects/approved-premises-and-delius/.trivyignore
  projects/approved-premises-and-oasys/.trivyignore
  projects/create-and-vary-a-licence-and-delius/.trivyignore
  projects/custody-key-dates-and-delius/.trivyignore
  projects/make-recall-decisions-and-delius/.trivyignore
  projects/manage-pom-cases-and-delius/.trivyignore
  projects/offender-events-and-delius/.trivyignore
  projects/pre-sentence-reports-to-delius/.trivyignore
  projects/prison-case-notes-to-probation/.trivyignore
  projects/prison-custody-status-to-delius/.trivyignore
  projects/refer-and-monitor-and-delius/.trivyignore
  projects/risk-assessment-scores-to-delius/.trivyignore
  projects/tier-to-delius/.trivyignore
  projects/unpaid-work-and-delius/.trivyignore
  projects/workforce-allocations-to-delius/.trivyignore
Labels: dependencies, security

#1214 PI-893 Re-add suppressions for CVE-2022-1471
  projects/approved-premises-and-delius/.trivyignore
  projects/approved-premises-and-oasys/.trivyignore
  projects/create-and-vary-a-licence-and-delius/.trivyignore
  projects/custody-key-dates-and-delius/.trivyignore
  projects/make-recall-decisions-and-delius/.trivyignore
  projects/manage-pom-cases-and-delius/.trivyignore
  projects/offender-events-and-delius/.trivyignore
  projects/pre-sentence-reports-to-delius/.trivyignore
  projects/prison-case-notes-to-probation/.trivyignore
  projects/prison-custody-status-to-delius/.trivyignore
  projects/refer-and-monitor-and-delius/.trivyignore
  projects/risk-assessment-scores-to-delius/.trivyignore
  projects/tier-to-delius/.trivyignore
  projects/unpaid-work-and-delius/.trivyignore
  projects/workforce-allocations-to-delius/.trivyignore
Labels: dependencies, security

#1215 PI-939 added notes to provision
  projects/unpaid-work-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ProvisionGenerator.kt
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/casedetails/CaseMapper.kt
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/casedetails/entity/DisabilityEntity.kt
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/casedetails/entity/ProvisionEntity.kt
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/casedetails/model/CaseDetails.kt
Labels: enhancement

#1222 PI-925 added column annotation for timestamp
  libs/audit/src/main/kotlin/uk/gov/justice/digital/hmpps/audit/entity/AuditedInteraction.kt
Labels: enhancement

#1229 PI-946 Validate PDF response from unpaid-work service
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/upwassessment/UPWAssessmentService.kt
  projects/unpaid-work-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/messaging/UPWAssessmentServiceTest.kt
Labels: enhancement

#1239 PI-577 Fix some column names
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/casesummary/Registration.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/casesummary/Release.kt
Labels: bug

#1240 PI-951 changed filename
  projects/unpaid-work-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/PersonManagerGenerator.kt
  projects/unpaid-work-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/AssessmentCompleteIntegrationTest.kt
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/common/entity/person/PersonWithManager.kt
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/upwassessment/UPWAssessmentService.kt
Labels: enhancement

#1241 PI-954 Trigger rebuild of person-search indexer
  projects/person-search-index-from-delius/README.md
Labels: bug

#1242 PI-577 Update MRD personal details responses, and ignore multiple active custodial events
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/AddressGenerator.kt
  projects/make-recall-decisions-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/CaseSummaryIntegrationTest.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/Overview.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/PersonalDetails.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/casesummary/Address.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/CaseSummaryService.kt
  projects/make-recall-decisions-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/CaseSummaryServiceTest.kt
Labels: enhancement

#1246 PI-577 Add endpoint for MAPPA and RoSH history
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/RegistrationGenerator.kt
  projects/make-recall-decisions-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/CaseSummaryIntegrationTest.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/controller/CaseSummaryController.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/MappaAndRoshHistory.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/casesummary/Event.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/casesummary/Registration.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/CaseSummaryService.kt
  projects/make-recall-decisions-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/api/controller/CaseSummaryControllerTest.kt
  projects/make-recall-decisions-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/CaseSummaryServiceTest.kt
  projects/make-recall-decisions-and-delius/tech-docs/source/draft-api-spec.yaml
Labels: enhancement
