Repository ministryofjustice/hmpps-probation-integration-services, pull requests merged in 2023-05, with the labels that each got.

#1492 PI-961: Allow Ctrl-O to access development EPF API
  projects/effective-proposal-framework-and-delius/deploy/values.yaml
Labels: enhancement

#1491 PI-784: Document Auth for Approved Premises and Delius Service
  projects/approved-premises-and-delius/README.md
Labels: enhancement

#1498 PI-1010: API docs for unpaid work and delius
  projects/unpaid-work-and-delius/README.md
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/casedetails/CaseDetailsController.kt
  projects/unpaid-work-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/personaldetails/PersonController.kt
Labels: documentation, enhancement

#1499 PI-1036 Person details endpoint for sentence plan service
  projects/sentence-plan-and-delius/.trivyignore
  projects/sentence-plan-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/sentence-plan-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/PersonGenerator.kt
  projects/sentence-plan-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/PersonManagerGenerator.kt
  projects/sentence-plan-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ProviderGenerator.kt
  projects/sentence-plan-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ReferenceDataGenerator.kt
  projects/sentence-plan-and-delius/src/dev/resources/local-public-key.pub
  projects/sentence-plan-and-delius/src/dev/resources/simulations/__files/hmpps-auth-token-body.json
  projects/sentence-plan-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/IntegrationTest.kt
  projects/sentence-plan-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/SentencePlanIntegrationTest.kt
  projects/sentence-plan-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/ApiController.kt
  projects/sentence-plan-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/CaseDetailsController.kt
  projects/sentence-plan-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/model/CaseDetails.kt
  projects/sentence-plan-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/Person.kt
  projects/sentence-plan-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/PersonDetailsService.kt
  projects/sentence-plan-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/ReferenceData.kt
  projects/sentence-plan-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/Staff.kt
  projects/sentence-plan-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/Team.kt
Labels: enhancement

#1505 PI-1019 Update to return tier description
  projects/sentence-plan-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/SentencePlanIntegrationTest.kt
  projects/sentence-plan-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/PersonDetailsService.kt
Labels: enhancement

#1436 PI-577 Remove staff code endpoint
  projects/make-recall-decisions-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/StaffIntegrationTest.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/controller/UserController.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/user/staff/StaffRepository.kt
Labels: enhancement

#1510 PI-1013 updates to appointment notes
  projects/refer-and-monitor-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/contact/entity/Contact.kt
Labels: enhancement

#1511 PI-1060 Tutorial documentation
  doc/tech-docs/source/guides.html.md.erb
Labels: documentation, enhancement

#1522 PI-988 Switch to OpenSearch
  projects/person-search-index-from-delius/container/scripts/monitor-reindexing.sh
  projects/person-search-index-from-delius/deploy/templates/contact-reindex-cronjob.yml
  projects/person-search-index-from-delius/deploy/templates/person-reindex-cronjob.yml
  projects/person-search-index-from-delius/deploy/values-dev.yml
  projects/person-search-index-from-delius/deploy/values-preprod.yml
  projects/person-search-index-from-delius/deploy/values-prod.yml
  projects/person-search-index-from-delius/deploy/values.yaml
Labels: enhancement

#1526 PI-1068 deal with requirements without main category
  projects/tier-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/TierDetailsService.kt
  projects/tier-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/entity/RequirementEntity.kt
Labels: bug

#1539 PI-1080 Respond with 200 OK from appointments endpoint
  projects/refer-and-monitor-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/MergeAppointmentIntegrationTest.kt
  projects/refer-and-monitor-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/resource/ReferralResource.kt
Labels: bug

#1544 PI-1083 Increase contact index rebuild timeout
  projects/person-search-index-from-delius/container/scripts/monitor-reindexing.sh
  projects/person-search-index-from-delius/deploy/templates/contact-reindex-cronjob.yml
Labels: bug

#1547 PI-1073 Probation area endpoint
  projects/pathfinder-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/pathfinder-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ProbationAreaGenerator.kt
  projects/pathfinder-and-delius/src/dev/resources/local-public-key.pub
  projects/pathfinder-and-delius/src/dev/resources/simulations/__files/hmpps-auth-token-body.json
  projects/pathfinder-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/IntegrationTest.kt
  projects/pathfinder-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/ProbationAreaIntegrationTest.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/ApiController.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/ProbationAreasController.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/entity/ProbationAreaEntity.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/model/ProbationArea.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/ProbationAreaService.kt
Labels: enhancement

#1551 PI-1091 Update `delius-db` profile name to match README
  projects/approved-premises-and-delius/src/main/resources/application.yml
  projects/court-case-and-delius/src/main/resources/application.yml
  projects/create-and-vary-a-licence-and-delius/src/main/resources/application.yml
  projects/custody-key-dates-and-delius/src/main/resources/application.yml
  projects/effective-proposal-framework-and-delius/src/main/resources/application.yml
  projects/make-recall-decisions-and-delius/src/main/resources/application.yml
  projects/manage-pom-cases-and-delius/src/main/resources/application.yml
  projects/offender-events-and-delius/src/main/resources/application.yml
  projects/pathfinder-and-delius/src/main/resources/application.yml
  projects/pre-sentence-reports-to-delius/src/main/resources/application.yml
  projects/prison-case-notes-to-probation/src/main/resources/application.yml
  projects/prison-custody-status-to-delius/src/main/resources/application.yml
  projects/refer-and-monitor-and-delius/src/main/resources/application.yml
  projects/sentence-plan-and-delius/src/main/resources/application.yml
  projects/tier-to-delius/src/main/resources/application.yml
  projects/unpaid-work-and-delius/src/main/resources/application.yml
  projects/workforce-allocations-to-delius/src/main/resources/application.yml
  templates/projects/api-client-and-server/src/main/resources/application.yml
  templates/projects/api-server/src/main/resources/application.yml
  templates/projects/message-listener-with-api-client-and-server/src/main/resources/application.yml
  templates/projects/message-listener-with-api-client/src/main/resources/application.yml
  templates/projects/message-listener/src/main/resources/application.yml
Labels: bug

#1552 PI-1072 added court appearances endpoint
  projects/pathfinder-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/pathfinder-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/CourtAppearanceGenerator.kt
  projects/pathfinder-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/CourtAppearancesIntegrationTest.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/CourtAppearancesController.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/entity/CourtAppearanceEntity.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/entity/ReferenceData.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/model/CourtAppearance.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/CourtAppearanceService.kt
Labels: enhancement

#1556 PI-1040: Document make recall decisions and delius
  projects/make-recall-decisions-and-delius/README.md
  projects/make-recall-decisions-and-delius/tech-docs/source/async-api-reference.html.md.erb
  projects/make-recall-decisions-and-delius/tech-docs/source/img/make-recall-decisions-and-delius-context-map.png
  projects/make-recall-decisions-and-delius/tech-docs/spec/async-api.yaml
Labels: documentation, enhancement

#1557 PI-1075 added convictions endpoint
  projects/pathfinder-and-delius/.trivyignore
  projects/pathfinder-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/pathfinder-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ConvictionEventGenerator.kt
  projects/pathfinder-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/ConvictionsIntegrationTest.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/ConvictionController.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/entity/ConvictionEventEntity.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/model/Conviction.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/ConvictionService.kt
Labels: enhancement

#1566 PI-1112 Log requests to Alfresco
  projects/unpaid-work-and-delius/deploy/values-prod.yml
Labels: enhancement

#1568 PI-1113 Rebuild caseload after tier update
  projects/tier-to-delius/deploy/database/access.yml
  projects/tier-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/tier/TierService.kt
Labels: enhancement

#1570 PI-1117 Add workflow for upgrading Gradle wrapper + PI-1105 move wrapper validation
  .github/workflows/build.yml
  .github/workflows/gradle.yml
Labels: enhancement

#1571 PI-1025 Move businessHoursOnly to generic-prometheus-alerts values
  projects/approved-premises-and-delius/deploy/values-dev.yml
  projects/approved-premises-and-delius/deploy/values-preprod.yml
  projects/approved-premises-and-oasys/deploy/values-dev.yml
  projects/approved-premises-and-oasys/deploy/values-preprod.yml
  projects/court-case-and-delius/deploy/values-dev.yml
  projects/court-case-and-delius/deploy/values-preprod.yml
  projects/create-and-vary-a-licence-and-delius/deploy/values-dev.yml
  projects/create-and-vary-a-licence-and-delius/deploy/values-preprod.yml
  projects/custody-key-dates-and-delius/deploy/values-dev.yml
  projects/custody-key-dates-and-delius/deploy/values-preprod.yml
  projects/custody-key-dates-and-delius/deploy/values-prod.yml
  projects/effective-proposal-framework-and-delius/deploy/values-dev.yml
  projects/effective-proposal-framework-and-delius/deploy/values-preprod.yml
  projects/make-recall-decisions-and-delius/deploy/values-dev.yml
  projects/make-recall-decisions-and-delius/deploy/values-preprod.yml
  projects/manage-pom-cases-and-delius/deploy/values-dev.yml
  projects/manage-pom-cases-and-delius/deploy/values-preprod.yml
  projects/offender-events-and-delius/deploy/values-dev.yml
  projects/offender-events-and-delius/deploy/values-preprod.yml
  projects/pathfinder-and-delius/deploy/values-dev.yml
  projects/pathfinder-and-delius/deploy/values-preprod.yml
  projects/person-search-index-from-delius/deploy/values-dev.yml
  projects/person-search-index-from-delius/deploy/values-preprod.yml
  projects/pre-sentence-reports-to-delius/deploy/values-dev.yml
  projects/pre-sentence-reports-to-delius/deploy/values-preprod.yml
  projects/prison-case-notes-to-probation/deploy/values-dev.yml
  projects/prison-case-notes-to-probation/deploy/values-preprod.yml
  projects/prison-custody-status-to-delius/deploy/values-dev.yml
  projects/prison-custody-status-to-delius/deploy/values-preprod.yml
  projects/refer-and-monitor-and-delius/deploy/values-dev.yml
  projects/refer-and-monitor-and-delius/deploy/values-preprod.yml
  projects/risk-assessment-scores-to-delius/deploy/values-dev.yml
  projects/risk-assessment-scores-to-delius/deploy/values-preprod.yml
  projects/sentence-plan-and-delius/deploy/values-dev.yml
  projects/sentence-plan-and-delius/deploy/values-preprod.yml
  projects/tier-to-delius/deploy/values-dev.yml
  projects/tier-to-delius/deploy/values-preprod.yml
  projects/unpaid-work-and-delius/deploy/values-dev.yml
  projects/unpaid-work-and-delius/deploy/values-preprod.yml
  projects/workforce-allocations-to-delius/deploy/values-dev.yml
  projects/workforce-allocations-to-delius/deploy/values-preprod.yml
  templates/projects/api-client-and-server/deploy/values-dev.yml
  templates/projects/api-client-and-server/deploy/values-preprod.yml
  templates/projects/api-server/deploy/values-dev.yml
  templates/projects/api-server/deploy/values-preprod.yml
  templates/projects/message-listener-with-api-client-and-server/deploy/values-dev.yml
  templates/projects/message-listener-with-api-client-and-server/deploy/values-preprod.yml
  templates/projects/message-listener-with-api-client/deploy/values-dev.yml
  templates/projects/message-listener-with-api-client/deploy/values-preprod.yml
  templates/projects/message-listener/deploy/values-dev.yml
  templates/projects/message-listener/deploy/values-preprod.yml
Labels: bug

#1583 PI-1093 Add CRN to AppointmentNotFound query
  projects/refer-and-monitor-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/contact/ContactRepository.kt
  projects/refer-and-monitor-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/AppointmentService.kt
Labels: bug

#1589 PI-1126 Handle empty key dates
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/Conviction.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/RecommendationModel.kt
Labels: bug

#1580 PI-1117 Set the correct Java version when upgrading Gradle
  .github/workflows/gradle.yml
Labels: enhancement

#1590 PI-983 Replace jobs that have failed to start
  projects/person-search-index-from-delius/container/pipelines/contact/logstash-full-load.conf
  projects/person-search-index-from-delius/container/pipelines/person/logstash-full-load.conf
  projects/person-search-index-from-delius/container/scripts/monitor-reindexing.sh
  projects/person-search-index-from-delius/deploy/templates/contact-reindex-cronjob.yml
  projects/person-search-index-from-delius/deploy/templates/person-reindex-cronjob.yml
Labels: bug

#1591 PI-1114 Remove extra notes entries from OGRS contact
  projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/RiskAssessmentService.kt
Labels: bug

#1597 PI-1128 Return 404 for missing Alfresco documents
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/DocumentService.kt
  projects/make-recall-decisions-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/DocumentServiceTest.kt
Labels: bug
