Repository ministryofjustice/hmpps-probation-integration-services, pull requests merged in 2023-06, with the labels that each got.

#1659 PI-1095 Make username case-insensitive
  projects/make-recall-decisions-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/UserIntegrationTest.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/user/details/UserDetailsRepository.kt
Labels: bug

#1660 PI-1139 Remove transitive LDAP dependency from commons
  libs/commons/build.gradle.kts
Labels: bug

#1735 PI-1133 Updated SQL for SR28 changes
  projects/person-search-index-from-delius/container/pipelines/person/statement.sql
Labels: enhancement

#1746 PI-1160 Remove old feature flags
  projects/prison-custody-status-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/ImportantStrings.kt
  projects/prison-custody-status-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/recall/RecallService.kt
  projects/prison-custody-status-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/recall/RecallServiceTest.kt
  projects/prison-custody-status-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/recall/RecallServiceTestBase.kt
  projects/prison-custody-status-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/recall/TemporaryAbsenceRecallTests.kt
  projects/risk-assessment-scores-to-delius/build.gradle.kts
  projects/risk-assessment-scores-to-delius/deploy/values-prod.yml
  projects/risk-assessment-scores-to-delius/src/dev/resources/simulations/mappings/feature-flags.json
  projects/risk-assessment-scores-to-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/FeatureFlagIntegrationTest.kt
  projects/risk-assessment-scores-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
  projects/risk-assessment-scores-to-delius/src/main/resources/application.yml
  projects/risk-assessment-scores-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/messaging/HandlerTest.kt
Labels: enhancement

#1748 PI-1058 Merge tech docs before publishing
  .github/workflows/docs.yml
Labels: bug

#1751 PI-983 Disable provenance for Docker builds
  .github/actions/docker-build/action.yml
Labels: bug

#1754 PI-1172 Fix commons tests and ensure tests are run in "check" task
  build.gradle.kts
  libs/commons/build.gradle.kts
Labels: bug

#1755 PI-1173 Handle disability notes CLOB
  projects/person-search-index-from-delius/container/pipelines/person/statement.sql
Labels: bug

#1757 PI-1174 Remove Sonar analysis from the pipeline
  .github/workflows/analyse.yml
  .github/workflows/build.yml
Labels: enhancement

#1758 PI-1174 Fix moving Sonar analysis out of pipeline
  .github/actions/analyse/action.yml
  .github/actions/merge-changes/action.yml
  .github/workflows/analyse.yml
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/pipeline.yml
Labels: bug

#1786 PI-1092 Added domain-events-and-delius service
  .github/workflows/access.yml
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/docs.yml
  .github/workflows/end-to-end-tests.yml
  .github/workflows/suppress-trivy.yml
  .idea/runConfigurations/domain-events-and-delius.xml
  doc/tech-docs/source/index.html.md.erb
  libs/commons/src/main/kotlin/uk/gov/justice/digital/hmpps/telemetry/TelemetryService.kt
  projects/domain-events-and-delius/.trivyignore
  projects/domain-events-and-delius/README.md
  projects/domain-events-and-delius/applicationinsights.json
  projects/domain-events-and-delius/build.gradle.kts
  projects/domain-events-and-delius/deploy/Chart.yaml
  projects/domain-events-and-delius/deploy/database/access.yml
  projects/domain-events-and-delius/deploy/values-dev.yml
  projects/domain-events-and-delius/deploy/values-preprod.yml
  projects/domain-events-and-delius/deploy/values-prod.yml
  projects/domain-events-and-delius/deploy/values.yaml
  projects/domain-events-and-delius/settings.gradle.kts
  projects/domain-events-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/domain-events-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/DomainEventGenerator.kt
  projects/domain-events-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/UserGenerator.kt
  projects/domain-events-and-delius/src/dev/resources/messages/manual-ogrs-attributes.json
  projects/domain-events-and-delius/src/dev/resources/messages/manual-ogrs.json
  projects/domain-events-and-delius/src/dev/resources/messages/registration-added-attributes.json
  projects/domain-events-and-delius/src/dev/resources/messages/registration-added.json
  projects/domain-events-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/IntegrationTest.kt
  projects/domain-events-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/App.kt
  projects/domain-events-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/DomainEvent.kt
  projects/domain-events-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/MessageAttribute.kt
  projects/domain-events-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/scheduling/Scheduler.kt
  projects/domain-events-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/DomainEventService.kt
  projects/domain-events-and-delius/src/main/resources/application.yml
  projects/domain-events-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/scheduling/SchedulerTest.kt
  projects/domain-events-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/DomainEventServiceTest.kt
  projects/domain-events-and-delius/tech-docs/.gitignore
  projects/domain-events-and-delius/tech-docs/.template_version
  projects/domain-events-and-delius/tech-docs/Gemfile
  projects/domain-events-and-delius/tech-docs/Gemfile.lock
  projects/domain-events-and-delius/tech-docs/config.rb
  projects/domain-events-and-delius/tech-docs/config/tech-docs.yml
  projects/domain-events-and-delius/tech-docs/source/index.html.md.erb
  projects/domain-events-and-delius/tech-docs/source/javascripts/application.js
  projects/domain-events-and-delius/tech-docs/source/stylesheets/print.css.scss
  projects/domain-events-and-delius/tech-docs/source/stylesheets/screen-old-ie.css.scss
  projects/domain-events-and-delius/tech-docs/source/stylesheets/screen.css.scss
  settings.gradle.kts
Labels: enhancement

#1808 PI-1092 Update HMPPS Domain Events topic secret
  projects/domain-events-and-delius/deploy/values.yaml
Labels: bug

#1818 PI-1185 Suppress CVE-2023-34455 in Logstash image
  .github/dependabot.yml
  projects/person-search-index-from-delius/.trivyignore
  projects/person-search-index-from-delius/container/Dockerfile
Labels: dependencies, security

#1823 PI-1185 Fix dependabot path
  .github/dependabot.yml
Labels: bug

#1825 PI-1191 Disable index auto-creation
  projects/person-search-index-from-delius/container/scripts/startup.sh
Labels: bug

#1826 PI-1178 Migrate to service accounts for SQS/SNS access
  .github/workflows/bootstrap.yml
  projects/approved-premises-and-delius/deploy/values.yaml
  projects/custody-key-dates-and-delius/deploy/values.yaml
  projects/domain-events-and-delius/deploy/values.yaml
  projects/make-recall-decisions-and-delius/deploy/values.yaml
  projects/manage-pom-cases-and-delius/deploy/values.yaml
  projects/offender-events-and-delius/README.md
  projects/offender-events-and-delius/deploy/values.yaml
  projects/person-search-index-from-delius/container/pipelines/contact/logstash-dlq.conf
  projects/person-search-index-from-delius/container/pipelines/contact/logstash-full-load.conf
  projects/person-search-index-from-delius/container/pipelines/contact/logstash-incremental.conf
  projects/person-search-index-from-delius/container/pipelines/person/logstash-dlq.conf
  projects/person-search-index-from-delius/container/pipelines/person/logstash-full-load.conf
  projects/person-search-index-from-delius/container/pipelines/person/logstash-incremental.conf
  projects/person-search-index-from-delius/deploy/templates/contact-reindex-cronjob.yml
  projects/person-search-index-from-delius/deploy/templates/person-reindex-cronjob.yml
  projects/person-search-index-from-delius/deploy/values.yaml
  projects/person-search-index-from-delius/docker-compose.yml
  projects/pre-sentence-reports-to-delius/deploy/values.yaml
  projects/prison-case-notes-to-probation/deploy/values.yaml
  projects/prison-custody-status-to-delius/deploy/values.yaml
  projects/refer-and-monitor-and-delius/deploy/values.yaml
  projects/risk-assessment-scores-to-delius/deploy/values.yaml
  projects/tier-to-delius/deploy/values.yaml
  projects/unpaid-work-and-delius/deploy/values.yaml
  projects/workforce-allocations-to-delius/deploy/values.yaml
  templates/projects/message-listener-with-api-client-and-server/deploy/values.yaml
  templates/projects/message-listener-with-api-client/deploy/values.yaml
  templates/projects/message-listener/deploy/values.yaml
  templates/sqs.tf
Labels: enhancement

#1832 PI-1178 Add STS dependency for IRSA
  settings.gradle.kts
Labels: enhancement

#1835 PI-1213 Ensure cache is read-only for branch builds
  .github/actions/cloud-platform-deploy/action.yml
  .github/workflows/build.yml
Labels: bug

#1836 PI-1178 Fix serviceAccountName field
  projects/custody-key-dates-and-delius/deploy/values.yaml
  projects/domain-events-and-delius/deploy/values.yaml
  projects/make-recall-decisions-and-delius/deploy/values.yaml
  projects/manage-pom-cases-and-delius/deploy/values.yaml
  projects/offender-events-and-delius/deploy/values.yaml
  projects/person-search-index-from-delius/deploy/templates/contact-reindex-cronjob.yml
  projects/person-search-index-from-delius/deploy/templates/person-reindex-cronjob.yml
  projects/person-search-index-from-delius/deploy/values.yaml
  projects/pre-sentence-reports-to-delius/deploy/values.yaml
  projects/prison-case-notes-to-probation/deploy/values.yaml
  projects/prison-custody-status-to-delius/deploy/values.yaml
  projects/refer-and-monitor-and-delius/deploy/values.yaml
  projects/risk-assessment-scores-to-delius/deploy/values.yaml
  projects/tier-to-delius/deploy/values.yaml
  projects/unpaid-work-and-delius/deploy/values.yaml
  projects/workforce-allocations-to-delius/deploy/values.yaml
  templates/projects/message-listener-with-api-client-and-server/deploy/values.yaml
  templates/projects/message-listener-with-api-client/deploy/values.yaml
  templates/projects/message-listener/deploy/values.yaml
Labels: bug

#1839 PI-1220 Set NSI outcome on AP departure
  projects/approved-premises-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ReferenceDataGenerator.kt
  projects/approved-premises-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/MessagingIntegrationTest.kt
  projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/nonstatutoryintervention/entity/Nsi.kt
  projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/referencedata/ReferenceData.kt
  projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/referencedata/ReferenceDataRepository.kt
  projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/NsiService.kt
  projects/approved-premises-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/ApprovedPremisesServiceTest.kt
Labels: enhancement

#1838 PI-1212 Fail end-to-end test when results are missing
  .github/workflows/end-to-end-tests.yml
Labels: bug

#1845 PI-1178 Reduce frequency of AWS SDK updates
  .github/dependabot.yml
Labels: dependencies

#1847 PI-1178 Ignore patch versions instead of having separate schedules
  .github/dependabot.yml
Labels: bug

#1854 PI-1236 Use environment variables in Trivy suppression workflow
  .github/workflows/suppress-trivy.yml
Labels: bug
