Repository ministryofjustice/hmpps-probation-integration-services, pull requests merged in 2024-08, with the labels that each got.

#4091 PI-2348 - update enum text string
  projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/referencedata/ApprovedPremisesCategoryCode.kt
  projects/approved-premises-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/referencedata/ApprovedPremisesCategoryCodeTest.kt
Labels: enhancement

#4098 PI-2410 Switch to squash merge for Dependabot PR
  .github/workflows/dependabot.yml
Labels: enhancement

#4099 PI-2410 Use bot token for auto-approving PRs
  .github/workflows/dependabot.yml
Labels: enhancement

#4116 PI-2302 Switch to probation-integration-bot GitHub app
  .github/actions/format-code/action.yml
  .github/workflows/bootstrap.yml
  .github/workflows/dependabot.yml
  .github/workflows/format.yml
  .github/workflows/gradle.yml
  .github/workflows/pipeline.yml
  .github/workflows/readonly.yml
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle.kts
  tools/ingress-testing/api-client/gradle/wrapper/gradle-wrapper.jar
  tools/ingress-testing/api-client/gradle/wrapper/gradle-wrapper.properties
  tools/ingress-testing/api-client/gradlew
  tools/ingress-testing/api-client/gradlew.bat
Labels: enhancement

#4132 PI-2302 Fix Gradle wrapper upgrade after switch to GitHub app
  .github/workflows/gradle.yml
Labels: enhancement

#4134 PI-2302 Fix e2e tests in pipeline after switch to GitHub app
  .github/CODEOWNERS
  .github/workflows/pipeline.yml
Labels: bug

#4135 PI-2410 Re-usable Dependabot auto-merge action
  .github/actions/dependabot-automerge/action.yml
  .github/dependabot.yml
  .github/workflows/dependabot.yml
Labels: bug

#4139 PI-2410 Add checkout step before dependabot merge
  .github/workflows/dependabot.yml
Labels: enhancement

#4140 PI-2410 Update CODEOWNERS for dependabot
  .github/CODEOWNERS
Labels: bug

#4147 PI-2413 Use single active custodial event for prison assessments
  projects/assessment-summary-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/assessment-summary-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/PersonGenerator.kt
  projects/assessment-summary-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ReferenceDataGenerator.kt
  projects/assessment-summary-and-delius/src/dev/resources/messages/assessment-summary-produced-O123456.json
  projects/assessment-summary-and-delius/src/dev/resources/simulations/__files/assessment-summary-O123456.json
  projects/assessment-summary-and-delius/src/dev/resources/simulations/mappings/oasys-mappings.json
  projects/assessment-summary-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/IntegrationTest.kt
  projects/assessment-summary-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/person/entity/Disposal.kt
  projects/assessment-summary-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/person/entity/Event.kt
  projects/assessment-summary-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/AssessmentService.kt
Labels: enhancement

#4146 PI-2383 - add arrival and departure date to contact record
  projects/approved-premises-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/MessagingIntegrationInactiveTest.kt
  projects/approved-premises-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/MessagingIntegrationTest.kt
  projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/ReferralService.kt
Labels: enhancement

#4149 PI-2418 - add disposal dates to payload response
  projects/core-person-record-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/core-person-record-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/PersonGenerator.kt
  projects/core-person-record-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/CorePersonIntegrationTest.kt
  projects/core-person-record-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/PersonDetail.kt
  projects/core-person-record-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integration/delius/entity/Disposal.kt
  projects/core-person-record-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/PersonMapping.kt
  projects/core-person-record-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/PersonService.kt
Labels: enhancement

#4150 PI-2416 Don't change RoSH registrations when risk flags are null
  projects/assessment-summary-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/assessment-summary-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/IntegrationTest.kt
  projects/assessment-summary-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/RiskService.kt
Labels: enhancement

#4151 PI-2302 Remove need for GitHub token to get HMPPS IP allowlists
  .github/actions/cloud-platform-deploy/action.yml
  .github/workflows/deploy.yml
Labels: enhancement

#4154 PI-2302 Fix deployment following change to IP allow lists variable
  .github/actions/cloud-platform-deploy/action.yml
  .github/workflows/deploy.yml
Labels: enhancement

#4158 PI-2336: Cater for new response data for spo contact
  projects/workforce-allocations-to-delius/src/dev/resources/simulations/__files/get-event-allocation-body.json
  projects/workforce-allocations-to-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/AllocateEventIntegrationTest.kt
  projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/workforceallocations/AllocationDetail.kt
  projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/AllocateEventService.kt
Labels: enhancement

#4164 PI-2302 Switch to GitHub app for bootstrap workflow
  .github/actions/create-signed-pull-request/action.yml
  .github/actions/format-code/action.yml
  .github/workflows/bootstrap.yml
  .github/workflows/gradle.yml
Labels: enhancement

#4166 PI-2302 Bump commit action to 1.5.0
  .github/actions/create-signed-pull-request/action.yml
  .github/actions/format-code/action.yml
  .github/workflows/gradle.yml
Labels: dependencies, github_actions

#4173 PI-2420 Ignore repatriated cases entirely
  projects/prison-custody-status-to-delius/src/main/resources/application-prisoner-movement.yml
Labels: bug

#4174 PI-2426 - use new fields to populate a contact
  projects/approved-premises-and-delius/src/dev/resources/simulations/__files/approved-premises-booking-cancelled.json
  projects/approved-premises-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/MessagingIntegrationTest.kt
  projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/approvedpremises/EventDetails.kt
  projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/ContactService.kt
  projects/approved-premises-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/ReferralService.kt
Labels: enhancement

#4180 PI-2440 Ignore inactive teams
  projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/allocations/AllocationValidator.kt
  projects/workforce-allocations-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/allocations/AllocationValidatorTest.kt
Labels: enhancement

#4183 PI-2448 Remove workarounds for initial assessment summary issues
  libs/oauth-server/src/main/kotlin/uk/gov/justice/digital/hmpps/config/DocumentationConfig.kt
  projects/assessment-summary-and-delius/src/dev/resources/simulations/__files/assessment-summary-E123456.json
  projects/assessment-summary-and-delius/src/dev/resources/simulations/__files/assessment-summary-F123456.json
  projects/assessment-summary-and-delius/src/dev/resources/simulations/__files/assessment-summary-G123456.json
  projects/assessment-summary-and-delius/src/dev/resources/simulations/__files/assessment-summary-H123456.json
  projects/assessment-summary-and-delius/src/dev/resources/simulations/__files/assessment-summary-M123456.json
  projects/assessment-summary-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/oasys/OrdsClient.kt
  projects/assessment-summary-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/AssessmentService.kt
  projects/assessment-summary-and-delius/src/main/resources/application.yml
Labels: enhancement

#4194 PI-2470 Truncate long assessor name by initialising first name(s)
  projects/assessment-summary-and-delius/src/dev/resources/simulations/__files/assessment-summary-M123456.json
  projects/assessment-summary-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/IntegrationTest.kt
  projects/assessment-summary-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/AssessmentService.kt
Labels: enhancement

#4199 PI-2449: Updated pathfinder to be the same as soc
  projects/pathfinder-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/pathfinder-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ConvictionEventGenerator.kt
  projects/pathfinder-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/CourtAppearanceGenerator.kt
  projects/pathfinder-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/DetailsGenerator.kt
  projects/pathfinder-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/KeyDateGenerator.kt
  projects/pathfinder-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/NSIGenerator.kt
  projects/pathfinder-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ProbationAreaGenerator.kt
  projects/pathfinder-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/ConvictionsIntegrationTest.kt
  projects/pathfinder-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/CourtAppearancesIntegrationTest.kt
  projects/pathfinder-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/DetailsIntegrationTest.kt
  projects/pathfinder-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/ProbationAreaIntegrationTest.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/ConvictionController.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/CourtAppearancesController.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/DetailController.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/IdentifierType.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/controller/ProbationAreasController.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/entity/ConvictionEventEntity.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/entity/CourtAppearanceEntity.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/entity/DetailEntity.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/entity/KeyDate.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/entity/Nsi.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/entity/ProbationAreaEntity.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/entity/Release.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/model/BatchRequest.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/model/Conviction.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/model/CourtAppearance.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/model/Detail.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/ConvictionService.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/CourtAppearanceService.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/DetailService.kt
  projects/pathfinder-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/ProbationAreaService.kt
Labels: enhancement

#4201 PI-2480 Return 404 when staff code is not found
  projects/workforce-allocations-to-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/AllocationDemandService.kt
Labels: bug

#4203 PI-2482 Handle null offences in assessment summary response
  projects/assessment-summary-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/oasys/OrdsClient.kt
  projects/assessment-summary-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/AssessmentService.kt
Labels: bug

#4202 PI-2457: Added mappa endpoint to MPC
  projects/manage-pom-cases-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/manage-pom-cases-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/PersonGenerator.kt
  projects/manage-pom-cases-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ProviderGenerator.kt
  projects/manage-pom-cases-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ReferenceDataGenerator.kt
  projects/manage-pom-cases-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/RegistrationGenerator.kt
  projects/manage-pom-cases-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/MappaIntegrationTest.kt
  projects/manage-pom-cases-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/MappaDetail.kt
  projects/manage-pom-cases-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/resource/MappaResource.kt
  projects/manage-pom-cases-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/person/entity/registration/entity/Registration.kt
  projects/manage-pom-cases-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/provider/entity/Team.kt
  projects/manage-pom-cases-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/services/MappaService.kt
  projects/manage-pom-cases-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/services/service/MappaServiceTest.kt
Labels: enhancement
