Repository ministryofjustice/hmpps-probation-integration-services, pull requests merged in 2024-04, with the labels that each got.

#3564 PI-2035: Fix date time issue
  projects/manage-supervision-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ContactGenerator.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/overview/entity/Contact.kt
Labels: enhancement

#3563 PI-2019 Fix typo in increasing tier-to-delius resources
  projects/tier-to-delius/deploy/values-dev.yml
Labels: enhancement

#3578 PI-2050 Fallback to COM when officer is no longer active
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/PersonGenerator.kt
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/UserGenerator.kt
  projects/make-recall-decisions-and-delius/src/dev/resources/messages/recommendation-deleted-inactive-staff.json
  projects/make-recall-decisions-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/RecommendationIntegrationTest.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/RecommendationService.kt
Labels: enhancement

#3579 PI-2049: Risk DeRegistrations
  projects/manage-supervision-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/manage-supervision-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/PersonGenerator.kt
  projects/manage-supervision-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/RiskFlagIntegrationTest.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/risk/PersonRiskFlags.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/risk/RiskFlag.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/risk/RiskFlagRemoval.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/risk/Registration.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/RiskService.kt
  projects/manage-supervision-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/api/controller/RiskControllerTest.kt
  projects/manage-supervision-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/RiskServiceTest.kt
Labels: enhancement

#3581 PI-2049: Risk DeRegistrations
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/risk/Registration.kt
Labels: enhancement

#3582 PI-2049: Risk DeRegistrations
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/risk/Registration.kt
Labels: enhancement

#3585 PI-2019 Remove increased resources
  projects/tier-to-delius/deploy/values-dev.yml
Labels: enhancement

#3586 PI-2019 Update ingress-test to use production-only class
  tools/ingress-test/deploy/values.yaml
Labels: enhancement

#3587 PI-2049: Order the removed risk flags
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/RiskService.kt
Labels: enhancement

#3589 PI-2056 Handle null status details
  projects/cas2-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/client/approvedpremises/model/ApplicationStatus.kt
  projects/cas2-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/Cas2Service.kt
Labels: bug

#3588 PI-2055 Handle null contact start time
  projects/resettlement-passport-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/CreateAppointmentIntTests.kt
  projects/resettlement-passport-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/entity/Appointment.kt
  projects/resettlement-passport-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/AppointmentService.kt
Labels: bug

#3592 PI-2057 Switch to imprisonment-status-changed event
  projects/prison-identifier-and-delius/src/dev/resources/messages/prisoner-received-inactive-booking.json
  projects/prison-identifier-and-delius/src/dev/resources/messages/prisoner-received.json
  projects/prison-identifier-and-delius/src/dev/resources/messages/prisoner-status-changed-inactive-booking.json
  projects/prison-identifier-and-delius/src/dev/resources/messages/prisoner-status-changed.json
  projects/prison-identifier-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/ProbationMatchingIntegrationTest.kt
  projects/prison-identifier-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
Labels: enhancement

#3593 PI-2045 Bump Sonar to v5 and switch to new Gradle Enterprise plugin
  buildSrc/build.gradle.kts
  settings.gradle.kts
Labels: enhancement

#3595 PI-1284 Add tests for queue publisher
  libs/messaging/build.gradle.kts
  libs/messaging/src/main/kotlin/uk/gov/justice/digital/hmpps/publisher/QueuePublisher.kt
  libs/messaging/src/test/kotlin/uk/gov/justice/digital/hmpps/publisher/QueuePublisherTest.kt
Labels: enhancement

#3598 PI-2054: Added compliance and activity
  projects/manage-supervision-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/manage-supervision-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ContactGenerator.kt
  projects/manage-supervision-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/CourtAppearanceGenerator.kt
  projects/manage-supervision-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/CourtReportGenerator.kt
  projects/manage-supervision-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/PersonGenerator.kt
  projects/manage-supervision-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/personalDetails/PersonDetailsGenerator.kt
  projects/manage-supervision-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/ComplianceIntegrationTest.kt
  projects/manage-supervision-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/SentenceIntegrationTest.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/controller/ComplianceController.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/activity/Activity.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/compliance/Breach.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/compliance/Compliance.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/compliance/PersonCompliance.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/overview/Activity.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/overview/Compliance.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/overview/Order.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/overview/Overview.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/overview/PreviousOrders.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/compliance/Nsi.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/overview/entity/Contact.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/overview/entity/Event.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/overview/entity/Requirement.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/ActivityService.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/ComplianceService.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/OverviewService.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/ScheduleService.kt
  projects/manage-supervision-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/api/controller/ComplianceControllerTest.kt
  projects/manage-supervision-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/ComplianceServiceTest.kt
  projects/manage-supervision-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/OverviewServiceTest.kt
Labels: enhancement

#3601 PI-2054: Added event number and acceptable absence
  projects/manage-supervision-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/manage-supervision-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ContactGenerator.kt
  projects/manage-supervision-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/ComplianceIntegrationTest.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/compliance/Compliance.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/overview/Activity.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/ComplianceService.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/ScheduleService.kt
  projects/manage-supervision-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/api/controller/ComplianceControllerTest.kt
Labels: enhancement

#3602 PI-2062 Use SENTENCE_CHANGED offender event
  projects/prison-identifier-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/MergeIntegrationTest.kt
  projects/prison-identifier-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Converter.kt
  projects/prison-identifier-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
  projects/prison-identifier-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/OffenderEvent.kt
Labels: enhancement

#3596 Feature/pi 1939 mas probabtion history
  projects/manage-supervision-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/manage-supervision-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/CourtReportGenerator.kt
  projects/manage-supervision-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/OffenderManagerGenerator.kt
  projects/manage-supervision-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/PersonGenerator.kt
  projects/manage-supervision-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/personalDetails/PersonDetailsGenerator.kt
  projects/manage-supervision-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/SentenceIntegrationTest.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/controller/SentenceController.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/sentence/ProbationHistory.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/sentence/SentenceOverview.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/overview/entity/Event.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/personalDetails/entity/PersonalContactEntity.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/referencedata/entity/ReferenceData.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/referencedata/entity/ReferenceDataLinkedList.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/sentence/entity/OffenderManager.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/sentence/entity/SentenceRepository.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/SentenceService.kt
  projects/manage-supervision-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/SentenceServiceTest.kt
Labels: enhancement

#3605 PI-1939 - use alfresco id in response object instead of document id. …
  projects/manage-supervision-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/SentenceIntegrationTest.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/sentence/CourtDocument.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/personalDetails/entity/Document.kt
  projects/manage-supervision-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/SentenceServiceTest.kt
Labels: enhancement

#3609 PI-2063: Fixed order of sentences and added rarActivity flag
  projects/manage-supervision-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/ComplianceIntegrationTest.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/activity/Activity.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/overview/entity/Contact.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/overview/entity/Event.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/ScheduleService.kt
Labels: enhancement

#3613 PI-2070 Listen to OFFENDER_DETAILS_CHANGED messages
  projects/prison-identifier-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
Labels: enhancement

#3615 PI-2051 Enable prison-identifier-and-delius matching in prod
  projects/prison-identifier-and-delius/deploy/values-dev.yml
  projects/prison-identifier-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/MergeIntegrationTest.kt
  projects/prison-identifier-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/ProbationMatchingIntegrationTest.kt
  projects/prison-identifier-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/messaging/Handler.kt
Labels: enhancement

#3616 PI-2071 Disable graceful shutdown for integration tests
  projects/accredited-programmes-and-oasys/src/main/resources/application.yml
  projects/approved-premises-and-delius/src/main/resources/application.yml
  projects/approved-premises-and-oasys/src/main/resources/application.yml
  projects/arns-and-delius/src/main/resources/application.yml
  projects/assessment-summary-and-delius/src/main/resources/application.yml
  projects/cas2-and-delius/src/main/resources/application.yml
  projects/cas3-and-delius/src/main/resources/application.yml
  projects/core-person-record-and-delius/src/main/resources/application.yml
  projects/court-case-and-delius/src/main/resources/application.yml
  projects/create-and-vary-a-licence-and-delius/src/main/resources/application.yml
  projects/custody-key-dates-and-delius/src/main/resources/application.yml
  projects/domain-events-and-delius/src/main/resources/application.yml
  projects/dps-and-delius/src/main/resources/application.yml
  projects/effective-proposal-framework-and-delius/src/main/resources/application.yml
  projects/external-api-and-delius/src/main/resources/application.yml
  projects/hdc-licences-and-delius/src/main/resources/application.yml
  projects/hmpps-auth-and-delius/src/main/resources/application.yml
  projects/make-recall-decisions-and-delius/src/main/resources/application.yml
  projects/manage-offences-and-delius/src/main/resources/application.yml
  projects/manage-pom-cases-and-delius/src/main/resources/application.yml
  projects/manage-supervision-and-delius/src/main/resources/application.yml
  projects/manage-supervision-and-oasys/src/main/resources/application.yml
  projects/oasys-and-delius/src/main/resources/application.yml
  projects/offender-events-and-delius/src/main/resources/application.yml
  projects/opd-and-delius/src/main/resources/application.yml
  projects/pathfinder-and-delius/src/main/resources/application.yml
  projects/pre-sentence-reports-to-delius/src/main/resources/application.yml
  projects/prison-case-notes-to-probation/src/main/resources/application.yml
  projects/prison-custody-status-to-delius/src/main/resources/application.yml
  projects/prison-education-and-delius/src/main/resources/application.yml
  projects/prison-identifier-and-delius/src/main/resources/application.yml
  projects/prisoner-profile-and-delius/src/main/resources/application.yml
  projects/probation-search-and-delius/src/main/resources/application.yml
  projects/refer-and-monitor-and-delius/src/main/resources/application.yml
  projects/resettlement-passport-and-delius/src/main/resources/application.yml
  projects/risk-assessment-scores-to-delius/src/main/resources/application.yml
  projects/sentence-plan-and-delius/src/main/resources/application.yml
  projects/sentence-plan-and-oasys/src/main/resources/application.yml
  projects/soc-and-delius/src/main/resources/application.yml
  projects/tier-to-delius/src/main/resources/application.yml
  projects/unpaid-work-and-delius/src/main/resources/application.yml
  projects/workforce-allocations-to-delius/src/main/resources/application.yml
  templates/projects/api-client-and-server/src/main/resources/application.yml
  templates/projects/api-server/src/main/resources/application.yml
  templates/projects/message-listener-with-api-client-and-server/src/main/resources/application.yml
  templates/projects/message-listener-with-api-client/src/main/resources/application.yml
  templates/projects/message-listener/src/main/resources/application.yml
Labels: enhancement

#3617 PI-2069
  projects/accredited-programmes-and-oasys/deploy/values-prod.yml
  projects/approved-premises-and-oasys/deploy/values-prod.yml
  projects/assessment-summary-and-delius/deploy/values-prod.yml
  projects/manage-supervision-and-oasys/deploy/values-prod.yml
  projects/sentence-plan-and-oasys/deploy/values-prod.yml
Labels: enhancement

#3622 Feature/pi 1939 mas sentence requirements refactor
  projects/manage-supervision-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/PersonGenerator.kt
  projects/manage-supervision-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/SentenceIntegrationTest.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/sentence/Requirement.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/overview/entity/Requirement.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/SentenceService.kt
  projects/manage-supervision-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/SentenceServiceTest.kt
Labels: enhancement

#3629 PI-1939 - handle null code_description from r_standard_reference_list…
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/overview/entity/Requirement.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/SentenceService.kt
  projects/manage-supervision-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/SentenceServiceTest.kt
Labels: enhancement

#3631 PI-1939 - correct RQMNT_TERMINATION_REASON_ID column to be a long and…
  projects/manage-supervision-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/PersonGenerator.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/overview/entity/Requirement.kt
Labels: enhancement

#3630 PI-2074: Added communication and system generated flags
  projects/manage-supervision-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/manage-supervision-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ContactGenerator.kt
  projects/manage-supervision-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/ActivityIntegrationTest.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/activity/Activity.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/overview/entity/Contact.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/ComplianceService.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/OverviewService.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/ScheduleService.kt
Labels: enhancement

#3635 PI-2074: Multiple categories for contact type
  projects/manage-supervision-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ContactGenerator.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/overview/entity/Contact.kt
Labels: enhancement

#3632 PI-1939 - update document repo, as all documents to be downloaded are…
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/personalDetails/entity/Document.kt
Labels: enhancement

#3637 PI-2074: Make compliance activity specific to rar category
  projects/manage-supervision-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/ComplianceIntegrationTest.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/compliance/Compliance.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/ComplianceService.kt
  projects/manage-supervision-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/api/controller/ComplianceControllerTest.kt
Labels: enhancement

#3649 Feature/pi 2000 mas sentence tab view orders
  projects/manage-supervision-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/manage-supervision-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/PersonGenerator.kt
  projects/manage-supervision-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/OrderIntegrationTest.kt
  projects/manage-supervision-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/SentenceIntegrationTest.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/controller/SentenceController.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/sentence/PreviousOrder.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/sentence/PreviousOrderHistory.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/overview/entity/Event.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/OrdersService.kt
  projects/manage-supervision-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/OrderServiceTest.kt
Labels: enhancement

#3653 PI-2117
  projects/prison-custody-status-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/messaging/actions/UpdateLocationActionTest.kt
  projects/prison-custody-status-to-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/messaging/actions/UpdateStatusActionTest.kt
Labels: bug

#3657 PI-2019 Added source code for ingress testing
  .github/workflows/tools.yml
  tools/ingress-testing/README.md
  tools/ingress-testing/api-client/build.gradle.kts
  tools/ingress-testing/api-client/gradle/wrapper/gradle-wrapper.jar
  tools/ingress-testing/api-client/gradle/wrapper/gradle-wrapper.properties
  tools/ingress-testing/api-client/gradlew
  tools/ingress-testing/api-client/gradlew.bat
  tools/ingress-testing/api-client/settings.gradle.kts
  tools/ingress-testing/api-client/src/main/kotlin/uk/gov/justice/digital/hmpps/App.kt
  tools/ingress-testing/api-client/src/main/kotlin/uk/gov/justice/digital/hmpps/client/ApiClient.kt
  tools/ingress-testing/api-client/src/main/kotlin/uk/gov/justice/digital/hmpps/config/RestClientConfiguration.kt
  tools/ingress-testing/api-client/src/main/kotlin/uk/gov/justice/digital/hmpps/config/ThreadPoolConfig.kt
  tools/ingress-testing/api-client/src/main/kotlin/uk/gov/justice/digital/hmpps/test/TestHarness.kt
  tools/ingress-testing/api-client/src/main/resources/application.yml
  tools/ingress-testing/api-server/Dockerfile
  tools/ingress-testing/api-server/deploy/Chart.yaml
  tools/ingress-testing/api-server/deploy/values.yaml
  tools/ingress-testing/api-server/server.py
Labels: enhancement

#3670 Feature/pi 2000 mas sentence tab offences
  projects/manage-supervision-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/PersonGenerator.kt
  projects/manage-supervision-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/OffenceIntegrationTest.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/controller/SentenceController.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/offence/Offence.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/offence/Offences.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/sentence/PreviousOrderHistory.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/overview/entity/Event.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/sentence/entity/SentenceRepository.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/OffenceService.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/OrdersService.kt
  projects/manage-supervision-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/OffenceServiceTest.kt
Labels: enhancement

#3677 PI-2079 Update Trivy suppressions
  .github/workflows/security.yml
  .trivyignore
  projects/accredited-programmes-and-oasys/.trivyignore
  projects/approved-premises-and-delius/.trivyignore
  projects/approved-premises-and-oasys/.trivyignore
  projects/arns-and-delius/.trivyignore
  projects/assessment-summary-and-delius/.trivyignore
  projects/cas2-and-delius/.trivyignore
  projects/cas3-and-delius/.trivyignore
  projects/court-case-and-delius/.trivyignore
  projects/create-and-vary-a-licence-and-delius/.trivyignore
  projects/custody-key-dates-and-delius/.trivyignore
  projects/domain-events-and-delius/.trivyignore
  projects/dps-and-delius/.trivyignore
  projects/effective-proposal-framework-and-delius/.trivyignore
  projects/external-api-and-delius/.trivyignore
  projects/hdc-licences-and-delius/.trivyignore
  projects/hmpps-auth-and-delius/.trivyignore
  projects/make-recall-decisions-and-delius/.trivyignore
  projects/manage-offences-and-delius/.trivyignore
  projects/manage-pom-cases-and-delius/.trivyignore
  projects/manage-supervision-and-delius/.trivyignore
  projects/manage-supervision-and-oasys/.trivyignore
  projects/oasys-and-delius/.trivyignore
  projects/offender-events-and-delius/.trivyignore
  projects/opd-and-delius/.trivyignore
  projects/pathfinder-and-delius/.trivyignore
  projects/person-search-index-from-delius/.trivyignore
  projects/pre-sentence-reports-to-delius/.trivyignore
  projects/prison-case-notes-to-probation/.trivyignore
  projects/prison-custody-status-to-delius/.trivyignore
  projects/prison-education-and-delius/.trivyignore
  projects/prison-identifier-and-delius/.trivyignore
  projects/prisoner-profile-and-delius/.trivyignore
  projects/refer-and-monitor-and-delius/.trivyignore
  projects/resettlement-passport-and-delius/.trivyignore
  projects/risk-assessment-scores-to-delius/.trivyignore
  projects/sentence-plan-and-delius/.trivyignore
  projects/sentence-plan-and-oasys/.trivyignore
  projects/soc-and-delius/.trivyignore
  projects/tier-to-delius/.trivyignore
  projects/unpaid-work-and-delius/.trivyignore
  projects/workforce-allocations-to-delius/.trivyignore
Labels: enhancement

#3676 Bump generic-service Helm chart to 3.2
  projects/accredited-programmes-and-oasys/deploy/Chart.yaml
  projects/approved-premises-and-delius/deploy/Chart.yaml
  projects/approved-premises-and-oasys/deploy/Chart.yaml
  projects/arns-and-delius/deploy/Chart.yaml
  projects/assessment-summary-and-delius/deploy/Chart.yaml
  projects/cas2-and-delius/deploy/Chart.yaml
  projects/cas3-and-delius/deploy/Chart.yaml
  projects/core-person-record-and-delius/deploy/Chart.yaml
  projects/court-case-and-delius/deploy/Chart.yaml
  projects/create-and-vary-a-licence-and-delius/deploy/Chart.yaml
  projects/custody-key-dates-and-delius/deploy/Chart.yaml
  projects/domain-events-and-delius/deploy/Chart.yaml
  projects/dps-and-delius/deploy/Chart.yaml
  projects/effective-proposal-framework-and-delius/deploy/Chart.yaml
  projects/external-api-and-delius/deploy/Chart.yaml
  projects/feature-flags/deploy/Chart.yaml
  projects/hdc-licences-and-delius/deploy/Chart.yaml
  projects/hmpps-auth-and-delius/deploy/Chart.yaml
  projects/make-recall-decisions-and-delius/deploy/Chart.yaml
  projects/manage-offences-and-delius/deploy/Chart.yaml
  projects/manage-pom-cases-and-delius/deploy/Chart.yaml
  projects/manage-supervision-and-delius/deploy/Chart.yaml
  projects/manage-supervision-and-oasys/deploy/Chart.yaml
  projects/oasys-and-delius/deploy/Chart.yaml
  projects/offender-events-and-delius/deploy/Chart.yaml
  projects/opd-and-delius/deploy/Chart.yaml
  projects/pathfinder-and-delius/deploy/Chart.yaml
  projects/person-search-index-from-delius/deploy/Chart.yaml
  projects/pre-sentence-reports-to-delius/deploy/Chart.yaml
  projects/prison-case-notes-to-probation/deploy/Chart.yaml
  projects/prison-custody-status-to-delius/deploy/Chart.yaml
  projects/prison-education-and-delius/deploy/Chart.yaml
  projects/prison-identifier-and-delius/deploy/Chart.yaml
  projects/prisoner-profile-and-delius/deploy/Chart.yaml
  projects/probation-search-and-delius/deploy/Chart.yaml
  projects/refer-and-monitor-and-delius/deploy/Chart.yaml
  projects/resettlement-passport-and-delius/deploy/Chart.yaml
  projects/risk-assessment-scores-to-delius/deploy/Chart.yaml
  projects/sentence-plan-and-delius/deploy/Chart.yaml
  projects/sentence-plan-and-oasys/deploy/Chart.yaml
  projects/soc-and-delius/deploy/Chart.yaml
  projects/tier-to-delius/deploy/Chart.yaml
  projects/unpaid-work-and-delius/deploy/Chart.yaml
  projects/workforce-allocations-to-delius/deploy/Chart.yaml
  templates/projects/api-client-and-server/deploy/Chart.yaml
  templates/projects/api-server/deploy/Chart.yaml
  templates/projects/message-listener-with-api-client-and-server/deploy/Chart.yaml
  templates/projects/message-listener-with-api-client/deploy/Chart.yaml
  templates/projects/message-listener/deploy/Chart.yaml
  tools/ingress-testing/api-server/deploy/Chart.yaml
Labels: dependencies

#3683 PI-2065: Added team caseload endpoint
  projects/manage-supervision-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/UserIntegrationTest.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/controller/UserController.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/user/TeamCase.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/user/TeamCaseload.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/user/entity/User.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/UserService.kt
  projects/manage-supervision-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/api/controller/UserControllerTest.kt
  projects/manage-supervision-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/UserServiceTest.kt
Labels: enhancement

#3687 PI-2124: Changed AP doc query to use contact type
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/DataLoader.kt
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/ContactGenerator.kt
  projects/make-recall-decisions-and-delius/src/dev/kotlin/uk/gov/justice/digital/hmpps/data/generator/DocumentGenerator.kt
  projects/make-recall-decisions-and-delius/src/integrationTest/kotlin/uk/gov/justice/digital/hmpps/CaseSummaryIntegrationTest.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/document/DocumentRepository.kt
  projects/make-recall-decisions-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/recommendation/contact/entity/Contact.kt
Labels: enhancement

#3686 Add documentation for providers, PDUs and LAUs
  doc/tech-docs/source/concepts.html.md.erb
Labels: documentation

#3690 PI-2065: Only return teams where team end date is not set
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/user/entity/User.kt
Labels: enhancement

#3691 PI-2065: Check end date for team query
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/user/entity/User.kt
Labels: enhancement

#3692 PI-2138 Add sequence to AdditionalIdentifier entity
  projects/prison-identifier-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/entity/AdditionalIdentifier.kt
Labels: bug

#3696 PI-265: Added pagination to team caseload endpoint
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/controller/UserController.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/model/user/TeamCaseload.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/integrations/delius/user/entity/User.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/service/UserService.kt
  projects/manage-supervision-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/api/controller/UserControllerTest.kt
  projects/manage-supervision-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/service/UserServiceTest.kt
Labels: enhancement

#3697 PI-2135 Add user access endpoint for Manage a Supervision
  projects/manage-supervision-and-delius/build.gradle.kts
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/controller/CaseloadController.kt
  projects/manage-supervision-and-delius/src/main/kotlin/uk/gov/justice/digital/hmpps/api/controller/UserAccessController.kt
  projects/manage-supervision-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/api/controller/CaseloadControllerTest.kt
  projects/manage-supervision-and-delius/src/test/kotlin/uk/gov/justice/digital/hmpps/api/controller/UserAccessControllerTest.kt
Labels: enhancement

#3695 PI-2127: Add documentation for 'Create and Vary a Licence and Delius'
  projects/create-and-vary-a-licence-and-delius/README.md
  projects/create-and-vary-a-licence-and-delius/tech-docs/diag/create-and-vary-a-licence-activation-workflow-context-map.d2
  projects/create-and-vary-a-licence-and-delius/tech-docs/diag/create-and-vary-a-licence-api-context-map.d2
  projects/create-and-vary-a-licence-and-delius/tech-docs/diag/create-and-vary-a-licence-workflow-create-licence-condition.d2
  projects/create-and-vary-a-licence-and-delius/tech-docs/source/img/create-and-vary-a-licence-activation-workflow-context-map.svg
  projects/create-and-vary-a-licence-and-delius/tech-docs/source/img/create-and-vary-a-licence-api-context-map.svg
  projects/create-and-vary-a-licence-and-delius/tech-docs/source/img/create-and-vary-a-licence-workflow-create-licence-condition.svg
Labels: enhancement
